name: PR checks - Build operator images

on:
  pull_request:
    branches:
      - master

env:
  SDK_VERSION: "1.16.0"
  CONTAINER_RUNTIME: "podman"
  ARTIFACTS: "artifacts"
  REGISTRY_PREFIX: quay.io/redhat-developer
  REPO: servicebinding-operator

jobs:
  build-operator-images:
    name: "Build operator images (PR)"
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"

