name: PR checks - Build operator images

on:
  pull_request:
    branches:
      - master

env:
  SDK_VERSION: "1.3.0"
  CONTAINER_RUNTIME: "podman"
  ARTIFACTS: "artifacts"
  #OPERATOR_REPO_REF: quay.io/redhat-developer/servicebinding-operator
  OPERATOR_REPO_REF: quay.io/pmacik/sbo-pr-checks

jobs:
  build-operator-images:
    name: "Build operator images (PR)"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Setup CLI
        uses: ./.github/actions/setup-cli
        with:
          operator-sdk: true

      - name: Build images
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
          PR_SHA: ${{github.event.pull_request.head.sha}}
        run: |
          export TAG=pr-${PR_NUMBER}-${PR_SHA:0:8}
          export OPERATOR_IMAGE_REF=${OPERATOR_REPO_REF}:${TAG}
          export OPERATOR_BUNDLE_IMAGE_REF=${OPERATOR_IMAGE_REF}-bundle
          export OPERATOR_INDEX_IMAGE_REF=${OPERATOR_IMAGE_REF}-index
          export OPERATOR_IMAGE_SHA_REF=${OPERATOR_IMAGE_REF}

          make SKIP_REGISTRY_LOGIN=true -o registry-login -o push-image -o push-bundle-image image bundle-image
          mkdir -p ${ARTIFACTS}
          podman save ${OPERATOR_IMAGE_REF} > ${ARTIFACTS}/operator-image.tar
          podman save ${OPERATOR_BUNDLE_IMAGE_REF} > ${ARTIFACTS}/operator-bundle.tar

          echo -n "${OPERATOR_INDEX_IMAGE_REF}" > ${ARTIFACTS}/operator-index.ref
          echo -n "${OPERATOR_BUNDLE_IMAGE_REF}" > ${ARTIFACTS}/operator-bundle.ref
          echo -n "${OPERATOR_IMAGE_REF}" > ${ARTIFACTS}/operator-image.ref

      - name: Archive images
        uses: actions/upload-artifact@v2
        with:
          name: operator-images-${{github.event.pull_request.number}}-${{github.event.pull_request.head.sha}}
          path: ${{env.ARTIFACTS}}/*.tar

      - name: Archive image references
        uses: actions/upload-artifact@v2
        with:
          name: operator-refs-${{github.event.pull_request.number}}-${{github.event.pull_request.head.sha}}
          path: ${{env.ARTIFACTS}}/*.ref
