name: PR checks - Build operator images

on:
  pull_request:
    branches:
      - master

env:
  GO111MODULE: on
  SDK_VERSION: "1.3.0"
  OPM_VERSION: "1.15.2"
  MINIKUBE_WANTUPDATENOTIFICATION: false
  MINIKUBE_WANTREPORTERRORPROMPT: false
  K8S_VERSION: "1.19.2"
  MINIKUBE_VERSION: "1.15.1"
  TEST_ACCEPTANCE_CLI: "kubectl"
  CONTAINER_RUNTIME: "podman"
  TEST_RESULTS: "out/acceptance-tests"

jobs:
  build-operator-images:
    name: "Build operator images (PR)"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.6"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Setup CLI
        uses: ./.github/actions/setup-cli

      - name: Build images
        run: |
          TAG=pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")-${GITHUB_SHA:0:8}
          export OPERATOR_IMAGE_REF=quay.io/pmacik/sbo-pr-checks:${TAG}
          export OPERATOR_BUNDLE_IMAGE_REF=${OPERATOR_IMAGE_REF}-bundle
          export OPERATOR_INDEX_IMAGE_REF=${OPERATOR_IMAGE_REF}-index
          export OPERATOR_IMAGE_SHA_REF=${OPERATOR_IMAGE_REF}

          make SKIP_REGISTRY_LOGIN=true -o registry-login -o push-image -o push-bundle-image image bundle-image
          mkdir -p artifacts
          podman save ${OPERATOR_IMAGE_REF} > artifacts/operator-image.tar
          podman save ${OPERATOR_BUNDLE_IMAGE_REF} > artifacts/operator-bundle.tar
          echo ${TAG} > artifacts/operator-tag.txt

      - name: Archive images
        uses: actions/upload-artifact@v2
        with:
          name: operator-images-${{github.event.pull_request.number}}-${{github.event.pull_request.head.sha}}
          path: artifacts/
