name: PR checks

on:
  pull_request:
    branches:
      - master

env:
  GO111MODULE: on
  SDK_VERSION: "1.16.0"
  MINIKUBE_WANTUPDATENOTIFICATION: false
  MINIKUBE_WANTREPORTERRORPROMPT: false
  K8S_VERSION: "1.19.2"
  MINIKUBE_VERSION: "1.21.0"
  TEST_ACCEPTANCE_CLI: "kubectl"
  TEST_RESULTS: "out/acceptance-tests"

jobs:
  commit-count:
    name: Single PR commit
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify number of commits in the PR is 1
        run: |
          COMMIT_COUNT="$(git log --oneline ${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}} | wc -l)"
          if ! [ $COMMIT_COUNT -eq 1 ]; then
            echo "Number of commits in the PR ($COMMIT_COUNT) must not be greater than one."
            exit 1
          fi

