name: "PR checks - Push operator images"

on:
  pull_request_target:
    branches:
      - master

env:
  REGISTRY_PREFIX: quay.io/redhat-developer
  REPO: servicebinding-operator

jobs:
  push-operator-images:
    name: "Push operator images (PR)"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
