name: "PR checks - Clean operator images"

on:
  pull_request_target:
    branches:
      - master
    types: [closed]

env:
  #OPERATOR_REPO_REF: quay.io/redhat-developer/servicebinding-operator
  OPERATOR_REPO_REF: quay.io/pmacik/sbo-pr-checks

jobs:
  clean-operator-images:
    name: "Clean operator images (PR)"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Clean operator, bundle and index images
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
        run: |
          echo "Placeholder for cleaning all ${OPERATOR_REPO_REF}:pr-${PR_NUMBER}-* images related to this PR #${PR_NUMBER}"
